코드 리뷰 및 리팩토링
NEXTERS16-phoneLetter/server pull request #17
Opened 2020-01-27 08:03 UTC by YeonBot

2020-01-27 13:19 UTC, hyerin6 approved these changes

2020-01-27 14:44 UTC, joongsoo requested changes

2020-01-27 14:44 UTC, joongsoo commented on src/main/java/com/nexters/phoneletter/user/controller/UserController.java
> +    return new ResponseEntity<User>(user, HttpStatus.CREATED);
클라이언트는 응답에 나가는 User의 정보로 무엇을 하나요?
필요하지 않다면 보내줄 필요가 있을까요?

2020-01-27 14:44 UTC, joongsoo commented on src/main/java/com/nexters/phoneletter/user/controller/UserController.java
> +  @PostMapping()
`()`도 필요 없을 것 같네요

2020-01-27 14:44 UTC, joongsoo commented on src/main/java/com/nexters/phoneletter/user/service/UserService.java
> +  public List<User> getAllUsers();
모든 유저를 조회하는 기능은 왜 필요한가요? 관리자라고 하더라도 조건없이 모든 유저를 조회하는 기능은 필요 없을 것 같네요.
필요한 기능만 만드는게 좋고, 그러기 위해서 기능정의가 필요한겁니다

2020-01-27 14:44 UTC, joongsoo commented on src/main/java/com/nexters/phoneletter/user/service/UserService.java
> +  public User createUser(UserSaveRequestDto userSaveRequestDto);
이름이 좀 더 비즈니스에 가깝게 `signUp`이 낫지 않을까요?

2020-01-27 14:44 UTC, joongsoo commented on src/main/java/com/nexters/phoneletter/user/controller/UserController.java
> +    User user = userService.createUser(userSaveRequestDto);
이메일 형식이 유효한지 검사도 해줘야하지 않을까요? `asdasdasd` 이런 값이 들어올 수도 있으니까요

2020-01-28 06:59 UTC, hyerin6 commented on src/main/java/com/nexters/phoneletter/user/controller/UserController.java
> +    User user = userService.createUser(userSaveRequestDto);
dto로 받는 값들 validation으로 검사하는거 어떨까요 😮

2020-01-28 07:25 UTC, hyerin6 commented on src/main/java/com/nexters/phoneletter/user/controller/UserController.java
> +    return new ResponseEntity<User>(user, HttpStatus.CREATED);
그럼 회원가입을 완료하고 나서 그 다음 바로 넘어가는 화면에서 user 정보가 필요하면 클라이언트가 다시 요청했을 때 요청하는 user 정보만 다시 보내줘야 하나요??

2020-01-28 14:32 UTC, joongsoo commented on src/main/java/com/nexters/phoneletter/user/controller/UserController.java
> +    return new ResponseEntity<User>(user, HttpStatus.CREATED);
회원가입이 완료되었을때는 
1. 로그인을 한 상태가 아니라면 유저의 정보를 보내줄 필요가 없을 것 같아요
    - "~~님 가입이 완료되었습니다" 이런 메세지를 띄워줄거면 필요할 수도 있겠네요
2. 회원가입 완료후에 바로 로그인을 시켜주는 방법도 있습니다. 그러면 응답값에 로그인한 유저의 정보가 필요하겠네요

2020-01-28 15:07 UTC, joongsoo commented
커밋메세지는 영어로 적고 깔끔하게 적어주세요
https://tech.ssut.me/write-a-good-git-commit-message/

2020-01-28 15:08 UTC, joongsoo commented on src/main/java/com/nexters/phoneletter/user/dto/UserRequestDto.java
> +        .phone1(phones[0])
폰번호를 왜 나눠서 저장하죠?

2020-02-01 03:13 UTC, merged